name: Run Tests
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install numpy pandas scikit-learn opencv-python jupyter nbconvert matplotlib scipy wandb

      - name: Convert Notebook to Python Script
        run: jupyter nbconvert --to notebook --execute Lab_5_Spring_2025.ipynb --output Lab_5_Spring_2025_executed.ipynb

      - name: Run Notebook & Log to WandB
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          export WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}
          python test_script.py
